### ISSUE TITLE
repository cleanup

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx-widgets#105]
I think it is a good time to review the repository contents with the following goals:

- review and remove no longer necessary functionalities
- reduce code complexity
- review dependencies (with the goal to reduce dependency complexity)

The following points come to mind:

- remove translation of widgets (going forward we can stick to english only)
- review kisa-specific functionalities and simplify the code

**Comment by marscher** [comment]
fixed by #107
