### ISSUE TITLE
re-release as "weldx-widgets" on conda-forge

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx-widgets#106]
currently, the package is available to install from conda using package name `weldx_widgets` while the package name on PyPi is `weldx-widgets`.
This adds complexity and confusion when switching between python and conda based workflows.

It would be good to find a way to make the package available on conda-forge using `weldx-widgets` as well (metapackage? re-release?)

**Comment by marscher** [comment]
I think conda-forge has a mechanism for renaming. I'll contact some staff there.

**Comment by CagtayFabry** [comment]
> [conda-forge/weldx_widgets-feedstock#4](https://github.com/conda-forge/weldx_widgets-feedstock/pull/4)

it's working! 👍🚀
