### ISSUE TITLE
Numpy 2 incompatiblity

### ISSUE THREAD

**Issue by marscher** [BAMWelDX/weldx-widgets#137]
A new printing behaviour has been enabled in Numpy 2.0 which leads to errors in the edit widget.

> [np.int64(42), np.int64(23), np.int64(12)]

used to be

> [42, 23, 12]

As these strings are interpreted using eval (which should probably also avoided), the creation of objects fails (There is no numpy in the namespace).

Also there is some trouble with Sympy, which cannot handle the printing behaviour which includes the complete types.

**Comment by marscher** [comment]
fixed by #139

**Comment by CagtayFabry** [comment]
closed via #139
