### ISSUE TITLE
tag `0.2.2` release

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/weldx-widgets#77]
The `0.2.2` release tag is missing on GitHub

please add the tag for the commit that was used for the latest pypi/conda release @marscher

**Comment by marscher** [comment]
![Screenshot_20220715_124014](https://user-images.githubusercontent.com/170287/179207885-fd3f418f-610b-41fd-b3c9-bd2de3ee2d02.png)

**Comment by marscher** [comment]
I think you got confused by the difference between tags and releases. The latter is a (pretty useless) Github feature, which is mainly used to attach binaries to a tag. As we deploy this lib to pypi and conda-forge, it didn't seem to be relevant.

**Comment by CagtayFabry** [comment]
ohh sorry that was my mistake, somehow I didn't even look for the tag and only the releases.
I had one local pip install that was showing as 0.2.1+something but I'm not sure why.

Thanks for clearing that up :)
